# ref: https://docs.travis-ci.com/user/languages/python
language: python
dist: xenial
sudo: true
services:
  - docker

matrix:
    include:
     - python: 3.4
       env: TOXENV=py34
     - python: 3.5
       env: TOXENV=py35
     - python: 3.5
       env: TOXENV=py35-functional
     - python: 3.6
       env: TOXENV=py36
     - python: 3.6
       env: TOXENV=py36-functional
     - python: 3.7
       env: TOXENV=py37
     - python: 3.7
       env: TOXENV=py37-functional

install:
  - pip install tox

script:
  - tox
